# This helm values file defines all infrastructure used by eShopOnContainers.
# It is used on all charts, so ** MUST BE INCLUDED ** on every deployment
blazorapp:
    secrets:
        {        
            "Cfg":{ # 在.net core中，環境變數都要前置cfg_ (如 cfg_EventBusConnection 、ApiGatewayConnection等              
              "ApiGatewayConnection": "Endpoint=http://apigw.ocelot:80"
            }
        }

servicehelloworldapi:
    secrets:
        {        
            "Cfg":{ # 在.net core中，環境變數都要前置cfg_ (如 cfg_EventBusConnection 、ApiGatewayConnection等
              "EventBusConnection": "HostName=rabbitmq;DispatchConsumersAsync=true;AutomaticRecoveryEnabled=true;UserName=guest;Password=guest",
              "ApiGatewayConnection": "Endpoint=http://apigw.ocelot:80"
            }
        }
serviceorderingapi:
    secrets:
        {        
            "Cfg":{ # 在.net core中，環境變數都要前置cfg_ (如 cfg_EventBusConnection 、ApiGatewayConnection等
              "EventBusConnection": "HostName=rabbitmq;DispatchConsumersAsync=true;AutomaticRecoveryEnabled=true;UserName=guest;Password=guest",
              "ApiGatewayConnection": "Endpoint=http://apigw.ocelot:80"
            }
        }
        
servicebankingapi:
    secrets:
        {        
            "Cfg":{ # 在.net core中，環境變數都要前置cfg_ (如 cfg_EventBusConnection 、ApiGatewayConnection等
              "EventBusConnection": "HostName=rabbitmq;DispatchConsumersAsync=true;AutomaticRecoveryEnabled=true;UserName=guest;Password=guest",
              "ApiGatewayConnection": "Endpoint=http://apigw.ocelot:80"
            }
        }    

global: # 目前尚未用到
 
  secrets:
    {        
        "Cfg":{
          "all_EventBusConnection": "HostName=rabbitmq;DispatchConsumersAsync=true;AutomaticRecoveryEnabled=true;UserName=guest;Password=guest",
          "all_ApiGatewayConnection": "Endpoint=http://apigw.ocelot:80"
        }
    }
  
