# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

blazorapp:
  fullnameOverride: blazorapp
  image:
      repository: acrsvr01.azurecr.io/apidemo/blazorapp
      tag: linux-latest 
      pullPolicy: Always
  ingress:
    enabled: true 
    annotations:
      kubernetes.io/ingress.class: traefik-azds  # Dev Spaces-specific
    hosts:
      - dev.blazorapp.r9qhhrc999.sea.azds.io  # Assumes deployment to the 'dev' space， azds show-context
    
rabbitmq:
    fullnameOverride: rabbitmq # Values.fullnameOverride 
    #username: guest
    #password: guest
    
      
apigwocelot:
    fullnameOverride: apigwocelot    
    image:
      repository: acrsvr01.azurecr.io/apidemo/apigwocelot
      tag: linux-latest 
      pullPolicy: Always

servicehelloworldapi:
    fullnameOverride: servicehelloworldapi    
    image:
      repository: acrsvr01.azurecr.io/apidemo/servicehelloworldapi
      tag: linux-latest
      pullPolicy: Always      
servicebankingapi:
    fullnameOverride: servicebankingapi    
    image:
      repository: acrsvr01.azurecr.io/apidemo/servicebankingapi
      tag: linux-latest 
      pullPolicy: Always
serviceorderingapi:
    fullnameOverride: serviceorderingapi    
    image:
      repository: acrsvr01.azurecr.io/apidemo/serviceorderingapi
      tag: linux-latest 
      pullPolicy: Always

