//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Support.Net.Core.Util {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RC {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RC() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Support.Net.Core.Util.RC", typeof(RC).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///  {
        ///    &quot;Name&quot;: &quot;PostAction&quot;,
        ///    &quot;Method&quot;: &quot;POST&quot;,
        ///    &quot;Path&quot;: &quot;/{action}&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;GetAction&quot;,
        ///    &quot;Method&quot;: &quot;GET&quot;,
        ///    &quot;Path&quot;: &quot;/{action}&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;ListContainers&quot;,
        ///    &quot;Method&quot;: &quot;GET&quot;,
        ///    &quot;Path&quot;: &quot;/containers/json&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;CreateContainer&quot;,
        ///    &quot;Method&quot;: &quot;POST&quot;,
        ///    &quot;Path&quot;: &quot;/containers/create&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;RemoveContainer&quot;,
        ///    &quot;Method&quot;: &quot;DELETE&quot;,
        ///    &quot;Path&quot;: &quot;/containers/{id}&quot;
        ///  },
        ///  {
        ///    &quot;Name&quot;: &quot;QueryOneContainer&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DockerAPIList {
            get {
                return ResourceManager.GetString("DockerAPIList", resourceCulture);
            }
        }
    }
}
