version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: service.rabbitmq
    networks:
      - dev_network

  service.ordering.api:
    image: ${DOCKER_REGISTRY-}serviceorderingapi
    build:
      context: .
      dockerfile: Service/Ordering/Service.Ordering.Api/Dockerfile
    container_name: service.ordering.api # 
    networks:
      - dev_network  

  service.banking.api:
    image: ${DOCKER_REGISTRY-}servicebankingapi
    build:
      context: .
      dockerfile: Service/Banking/Service.Banking.Api/Dockerfile
    container_name: service.banking.api
    networks:
      - dev_network

  apigw.ocelot:
    image: ${DOCKER_REGISTRY-}apigwocelot
    build:
      context: .
      dockerfile: BuildingBlocks/ApiGw/ApiGw.Ocelot/Dockerfile
    networks:
      - dev_network

  service.helloworld.api:
    image: ${DOCKER_REGISTRY-}servicehelloworldapi
    build:
      context: .
      dockerfile: Service/HelloWorld/Service.HelloWorld.Api/Dockerfile
    container_name: service.helloworld.api
    networks:
      - dev_network
networks:
  dev_network:
      driver: bridge
      #external:
      #    name: extnetwork #*** Manually create  using `docker network create extnetwork` first. ***#
