version: '3.4'

services: 
  blazorapp:
    image: ${REGISTRY:-apidemo}/blazorapp:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: Client/BlazorApp/Dockerfile
  apigw.ocelot:
    image: ${REGISTRY:-apidemo}/apigwocelot:${PLATFORM-linux}-${TAG-latest} # ${DOCKER_REGISTRY-}apigwocelot
    build:
      context: .
      dockerfile: BuildingBlocks/ApiGw/ApiGw.Ocelot/Dockerfile
    
  service.ordering.api:
    image: ${REGISTRY:-apidemo}/serviceorderingapi:${PLATFORM-linux}-${TAG-latest} #${DOCKER_REGISTRY-}serviceorderingapi
    build:
      context: .
      dockerfile: Service/Ordering/Service.Ordering.Api/Dockerfile
    
   
  service.banking.api:
    image: ${REGISTRY:-apidemo}/servicebankingapi:${PLATFORM-linux}-${TAG-latest} # ${DOCKER_REGISTRY-}servicebankingapi
    build:
      context: .
      dockerfile: Service/Banking/Service.Banking.Api/Dockerfile
    
    
  
  service.helloworld.api:
    image: ${REGISTRY:-apidemo}/servicehelloworldapi:${PLATFORM-linux}-${TAG-latest} # ${DOCKER_REGISTRY-}servicehelloworldapi
    build:
      context: .
      dockerfile: Service/HelloWorld/Service.HelloWorld.Api/Dockerfile
       
 
