version: '3.4'

services:
  rabbitmq:
    ports:
        - "15672:15672"
        - "5672:5672"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  service.ordering.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      #- ASPNETCORE_URLS=https://+:443;http://+:80 #*** 443 don't work ***
      ## ${EVENT_BUS} from .env file, if undefined then 'rabbitmq' is default.
      - EventBusConnection=${EVENT_BUS:-rabbitmq} 
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  

  service.banking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
      #- ASPNETCORE_URLS=https://+:443;http://+:80
      ## ${EVENT_BUS} from .env file, if undefined then 'rabbitmq' is default.
      - EventBusConnection=${EVENT_BUS:-rabbitmq}
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  apigw.ocelot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "88:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  service.helloworld.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      #- ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  blazorapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ApiGatewayConnection=${API_GATEWAY:-apigw.ocelot} 
    ports:
      - "66:80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
